[package]
name = "pcstat"
version = "0.1.0"
authors = ["Hanaasagi <ambiguous404@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
syscall = "0.2.1"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
clap = "2.33.0"
